name: flutter_template
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Firebase
  firebase_core: ^1.22.0
  firebase_auth: ^3.3.4
  firebase_storage: ^10.3.10
  firebase_messaging: ^11.2.5
  cloud_firestore: ^3.1.5
  cloud_functions: ^3.3.9
  geoflutterfire: ^3.0.3

  # Google
  google_sign_in: ^5.1.0
  googleapis: ^7.0.0

  # architecture
  riverpod: ^1.0.3
  flutter_riverpod: ^1.0.3
  freezed: ^2.1.0
  freezed_annotation: ^2.1.0
  go_router: ^3.0.2

  # api
  json_serializable: ^6.3.1
  http: ^0.13.3
  retrofit: 3.0.1
  logger: ^1.1.0

  # database
  sqflite: ^2.0.3
  drift: ^2.1.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.2
  shared_preferences: ^2.0.15

  flutter_local_notifications: ^9.2.0

  # UI
  flutter_signin_button: ^2.0.0
  intl: ^0.17.0
  flutter_platform_widgets: ^2.0.0
  location: ^4.4.0
  google_maps_flutter: ^2.2.2
  battery_plus: ^3.0.2


dev_dependencies:
  retrofit_generator: ^4.0.3
  build_runner: ^2.1.7
  fimber: ^0.6.5
  drift_dev: ^2.1.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  generate: true

  fonts:
   - family: NotoSans
     fonts:
       - asset: assets/fonts/NotoSansJP-Black.otf
       - asset: assets/fonts/NotoSansJP-Bold.otf
       - asset: assets/fonts/NotoSansJP-Light.otf
       - asset: assets/fonts/NotoSansJP-Medium.otf
       - asset: assets/fonts/NotoSansJP-Regular.otf
       - asset: assets/fonts/NotoSansJP-Thin.otf
